#@meta {author: "Paul Landes"}
#@meta {desc: "configure ", date: "2026-04-06"}


[import]
sections = tuple: llama_imp

[llama_imp]
type = condyaml
config_file = resource(zensols.lmtask): resources/llama.yml
# [llama_imp]
# type_map = dict: {'yml': 'importyaml', 'conf': 'importini'}
# config_files = tuple:
#   resource(zensols.lmtask): resources/llama.yml,
#   resource(zensols.lmtask): resources/default.conf



## Defaults
#
[lmtask_default]
# the default model (configured in the generator instance)
base_generator = lmtask_llama_base_generator
base_resource = lmtask_llama_base_resource
instruct_generator = lmtask_llama_instruct_generator
instruct_resource = lmtask_llama_instruct_resource
