#@meta {author: "Paul Landes"}
#@meta {desc: "dataset for supervised fine-tuning", date: "2026-04-11"}
#@meta {doc: "create new task: copy this, train-dataset-{base/instruct}, replace `_dataset`"}


## Defaults
#
default:
  data_dir: ${default:root_dir}/data/${lmtask_dataset:dataset_name}/${lmtask_dataset:model_name}

lmtask_default:
  base_resource: lmtask_dataset_inference_resource

lmtask_trainer_default:
  trainer_name: 'lmtask_trainer_hf'
  1.condition:
    if: ${lmtask_dataset:is_base}
    then:
      source_model: ${lmtask_default:base_model_id}
    else:
      source_model: ${lmtask_default:instruct_model_id}


## Trainer
#
lmtask_trainer_hf_source_resource:
  1.condition:
    if: ${lmtask_dataset:is_base}
    then:
      class_name: ${lmtask_default:base_resource_class}
    else:
      class_name: ${lmtask_default:instruct_resource_class}

lmtask_trainer_hf:
  train_source: 'instance: lmtask_dataset_train_source'
  eval_source: 'instance: lmtask_dataset_eval_source'

lmtask_dataset_train_source:
  class_name: zensols.lmtask.dataset.LoadedTaskDatasetFactory
  # the task that consumes the data, which will format each datapoint
  # specifically for that task's model
  task: 'instance: lmtask_task_dataset'

lmtask_dataset_eval_source:
  class_name: zensols.lmtask.dataset.LoadedTaskDatasetFactory
  task: 'instance: lmtask_task_dataset'


## Inference
#
lmtask_dataset_model_args:
  device_map: auto
  # uncomment to load weights as a 16-bit float
  #torch_dtype: float16
  # uncommen to add quantization
  #quantization_config: 'instance: lmtask_quant_4bit_config'

lmtask_dataset_inference_resource:
  condition:
    if: ${lmtask_dataset:is_base}
    then:
      class_name: ${lmtask_default:base_resource_class}
    else:
      class_name: ${lmtask_default:instruct_resource_class}
  model_desc: 'Model trained on the ${lmtask_dataset:dataset_name} dataset'
  model_args: 'instance: lmtask_dataset_model_args'
  model_id: '${lmtask_trainer_default:source_model}'
  peft_model_id: '${lmtask_trainer_default:peft_output_dir}'

lmtask_dataset_stash:
  class_name: zensols.db.sqlite.SqliteDbStash
  path: 'path: ${default:data_dir}/task/cache.sqlite3'

lmtask_dataset_caching_generator:
  class_name: zensols.lmtask.generate.CachingGenerator
  condition:
    if: ${lmtask_dataset:is_base}
    then:
      _delegate: 'alias: lmtask_default:base_generator'
    else:
      _delegate: 'alias: lmtask_default:instruct_generator'
  _stash: 'instance: lmtask_dataset_stash'

lmtask_task_dataset:
  description: 'Trained on the ${lmtask_dataset:dataset_name} dataset'
  1.condition:
    if: ${lmtask_dataset:is_base}
    then:
      class_name: zensols.lmtask.generate.GenerateTask
    else:
      class_name: zensols.lmtask.instruct.InstructTask
  2.condition:
    if: ${lmtask_dataset:is_base}
    then:
      request_class: 'class: zensols.lmtask.task.TaskRequest'
    else:
      request_class: 'class: zensols.lmtask.instruct.InstructTaskRequest'
  response_class: 'class: zensols.lmtask.task.TaskResponse'
  resource: 'alias: lmtask_default:base_resource'
  condition:
    if: ${lmtask_default:cache}
    then:
      generator: 'instance: lmtask_dataset_caching_generator'
    else:
      generator: '${lmtask_dataset_caching_generator:_delegate}'
