name: lmtask
channels:
  - defaults
dependencies:
  - python==3.11.11
  - numpy==1.25.2
  - nmslib==2.1.1
  - pip
  - pip:
      ## third party frameworks
      # inference
      - torch==2.2.2
      - transformers==4.48.3
      - bitsandbytes==0.42.0
      # parsing
      - partial-json-parser==0.2.1.1.post5
      # training
      - datasets==2.21.0
      - accelerate==0.34.2
      - peft==0.14.0
      - trl==0.8.6
      - xformers==0.0.25.post1
      # prompting
      - jinja2>=3.1
      ## framework
      - zensols.util==1.15.6
      - zensols.db==1.4.0
      - zensols.nlp==1.12.1
      # inference
      - zensols.deeplearn==1.13.8
