#@meta {author: "Paul Landes"}
#@meta {desc: "qwen model configuration", date: "2026-06-01"}


[import]
sections = tuple: dsr1qwen3_imp

[dsr1qwen3_imp]
type = condyaml
config_file = resource(zensols.lmtask): resources/models/dsr1qwen3.yml

[lmtask_default]
base_resource_class = zensols.lmtask.generate.ConfigGeneratorResource
base_generator = lmtask_dsr1qwen3_base_generator
base_resource = lmtask_dsr1qwen3_base_resource
instruct_resource_class = ${lmtask_default:base_resource_class}
instruct_generator = lmtask_dsr1qwen3_instruct_generator
instruct_resource = lmtask_dsr1qwen3_instruct_resource
# the model used for inference and training;
# there is no pretrained model; only the instruct is available
## models:
# deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
# deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
# deepseek-ai/DeepSeek-R1-Distill-Llama-8B
# deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
# deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
# deepseek-ai/DeepSeek-R1-Distill-Llama-70B
base_model_id = deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
instruct_model_id = ${lmtask_default:base_model_id}
