#@meta {author: "Paul Landes"}
#@meta {desc: "gemma model configuration", date: "2026-04-06"}


[import]
sections = tuple: gemma_imp

[gemma_imp]
type = condyaml
config_file = resource(zensols.lmtask): resources/models/gemma4.yml

[lmtask_default]
base_resource_class = zensols.lmtask.gemma4.Gemma4GeneratorResource
base_generator = lmtask_gemma_base_generator
base_resource = lmtask_gemma_base_resource
instruct_resource_class = ${lmtask_default:base_resource_class}
instruct_generator = lmtask_gemma_instruct_generator
instruct_resource = lmtask_gemma_instruct_resource
## the model used for inference (it is Instruct Tuned) and training
## large:
# - google/gemma-4-31B
# - google/gemma-4-31B-it
## mid:
# - google/gemma-4-E4B
# - google/gemma-4-E4B-it
## small:
# - google/gemma-4-E2B
# - google/gemma-4-E2B-it
#base_model_id = google/gemma-4-E4B
#instruct_model_id = google/gemma-4-E4B-it
base_model_id = google/gemma-4-E2B
instruct_model_id = google/gemma-4-E2B-it
