#@meta {author: "Paul Landes"}
#@meta {desc: "qwen model configuration", date: "2026-04-06"}


[import]
sections = tuple: qwen_imp

[qwen_imp]
type = condyaml
config_file = resource(zensols.lmtask): resources/models/qwen.yml

[lmtask_default]
base_generator = lmtask_qwen_base_generator
base_resource = lmtask_qwen_base_resource
instruct_generator = lmtask_qwen_instruct_generator
instruct_resource = lmtask_qwen_instruct_resource
base_model_id = Qwen/Qwen3-8B
instruct_model_id = ${lmtask_default:base_model_id}

[lmtask_trainer_default]
## the check point to train from
source_model = Qwen/Qwen3-8B
