#@meta {desc: "tiny story trainer config", date: "2025-02-03"}
#@meta {url: "https://colab.research.google.com/drive/1ef-tab5bhkvWmBOObepl1WgJvfvSzn5Q?usp=sharing"}
#@meta {doc: "some parameters overwrite defaults to make it easy to port this config"}


## Imports
#
project:
  import:
    model_imp:
      config_file: 'resource(zensols.lmtask): resources/models/gemma4.conf'
      merge: parent
      type: importini
    train_imp:
      config_file: 'resource(zensols.lmtask): resources/train-dataset.yml'
      merge: child
      type: importyaml


## Defaults
#
lmtask_dataset:
  dataset_name: tinystory
  model_name: gemma


## Train
#
lmtask_trainer_default:
  source_model: 'google/gemma-4-E2B'

lmtask_dataset_train_source:
  source: roneneldan/TinyStories
  load_args:
    split: 'train[:2500]'

lmtask_dataset_eval_source:
  source: roneneldan/TinyStories
  load_args:
    split: 'validation[:250]'

lmtask_trainer_hf_training_arguments:
  learning_rate: 5e-6
  num_train_epochs: 1
  optim: 'paged_adamw_32bit'
  lr_scheduler_type: 'cosine'
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  logging_steps: 2

lmtask_trainer_hf_peft:
  r: 128
  lora_alpha: 32
  lora_dropout: 0.05
