#@meta {author: "Paul Landes"}
#@meta {desc: "shared tinystory trained model config", date: "2026-04-12"}


lmtask_dataset_train_source:
  source: roneneldan/TinyStories
  load_args:
    split: 'train[:2500]'

lmtask_dataset_eval_source:
  source: roneneldan/TinyStories
  load_args:
    split: 'validation[:250]'

lmtask_trainer_hf_training_arguments:
  learning_rate: 5e-6
  num_train_epochs: 3
  optim: 'paged_adamw_32bit'
  lr_scheduler_type: 'cosine'
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  logging_steps: 2

lmtask_trainer_hf_peft:
  r: 128
  lora_alpha: 32
  lora_dropout: 0.05
